examples - org contents
headingAndLists2
	^ 'Any text 1.
* Any head 1
** Any head 2
any text
* Sessions
** Session Title 1
Session description 1.
*** Transcription
1. 03:45-06:24 Some text Q"Specific question" GQ"General question" c"keyword1" another text.
   1. 04:03-04:15 another c"keyword1" text
   2. 04:23-05:12 another text2 c"keyword2"
2. 06:24-07:23 c"keyword3" another text3
** Session Title 2
Session description 2.
*** Transcription
1. 03:45-06:24 Some text c"keyword1" Q"Specific question 1" GQ"General question 2" another text 2.
   1. 04:03-04:15 another text 3.
   2. 04:23-05:12 another text c"keyword3" 4.
2. 06:24-07:23 another text 5.
'